### ISSUE TITLE
Python error missing "setting"

### ISSUE THREAD

**Issue by pivipivi** [RoboDK/Plug-In-Interface#46]
Hello,

I am continuosly facing this issue:
![image](https://user-images.githubusercontent.com/124673676/217472165-9cc70797-c3b9-4114-bcf7-b77aeb62051e.png)

can anybody help me?

Thanks

**Comment by sambertrdk** [comment]
I updated the BoxSpawner and it should work now (not yet in the installer). You might need to remove and re-add the Spawner script in your station. Also, are you using the AppLoader of the new Add-in Manager?

**Comment by sjohnson-FLL** [comment]
I have a similar problem with the surface pattern generator. (also posted on the forum: https://robodk.com/forum/Thread-SURFACE-PATTERN-GENERATOR-FAILS?pid=14894#pid14894)

**Comment by sambertrdk** [comment]
_No module named 'Settings'_ indicates that the script is not able to find the App on disk (Settings.py).
This is an issue related to PYTHONPATH, which is populated by RoboDK and the Add-in Manager.
To resolve issues like these, you need to update the Add-in Manager (by updating RoboDK).

The issue reported by @sjohnson-FLL is able to find the App on disk (Settings.py), but crashes when loading a section header.
This issue was fixed in the RoboDK Python API, which you can update from PyPI or with the RoboDK installer.
